<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hzlGiri</name>
   <tag></tag>
   <elementGuidId>b544831d-10b6-466e-9926-be59e9ff92ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fast-login-btn.ng-star-inserted > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/fast-login-tr.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/dk-app[1]/div[@class=&quot;page-wrap&quot;]/dk-page-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;header home-page&quot;]/dk-header[1]/header[1]/div[@class=&quot;header&quot;]/a[@class=&quot;fast-login-btn ng-star-inserted&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
   </webElementXpaths>
</WebElementEntity>
